config/routes.rb
Rails.application.routes.draw do
  resources :journals do
    resources :entries
  end

  root "journals#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :journal

  validates :text, presence: true
end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :entries, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_journal, only: %i[new create edit show update destroy index]
  before_action :set_entry, only: %i[show update destroy edit]

  def new
    @entry = @journal.entries.build
  end

  def create
    @journal = Journal.find(params[:journal_id])
    @entry = @journal.entries.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.turbo_stream
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @entry = @journal.entries.find(params[:id])
  end

  def update
    @entry = @journal.entries.find(params[:id])

    respond_to do |format|
      if @entry.update(entry_params)
        format.turbo_stream
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @entry.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@entry) }
    end
  end

  private

  def set_journal
    @journal = Journal.find(params[:journal_id])
  end

  def set_entry
    @entry = @journal.entries.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:text)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  def index
    @journals = Journal.all
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.turbo_stream
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.turbo_stream
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @journal.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@journal) }
    end
  end

  private

  def set_journal
    @journal = Journal.find(params[:id])
  end

  def journal_params
    params.require(:journal).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_entry.html.erb
<%= turbo_frame_tag entry do %>
  <p>
    <strong>Title:</strong>
    <%= entry.text %>
  </p>

  <% if action_name != "show" %>
    <%= button_to "Destroy this entry",journal_entry_path(@journal, entry), method: :delete %>
    <%= link_to 'Edit this entry', edit_journal_entry_path(@journal, entry) %>
    <hr>
  <% end %>
<% end %>

app/views/entries/_form.html.erb
<%= form_with(model: [@journal, entry], class: "contents", id: "entry_form") do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= entry.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :text %>
    <%= form.text_area :text, required: true, data: { "validation-message": "Please enter some text for the entry." } %>
  </div>

  <div class="inline">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/create.turbo_stream.erb
<%= turbo_stream.prepend "entries" do %>
  <%= render @entry %>
<% end %>

<%= turbo_stream.replace "entry_form" do %>
  <%= render "form", entry: @journal.entries.new %>
<% end %>

app/views/entries/edit.html.erb
<%= turbo_frame_tag @entry do %>
  <div>
    <h1 class="font-bold text-4xl">Editing Entry</h1>

    <%= render "form", entry: @entry %>

    <%= link_to "Back to Journal", journal_entries_path(@journal) %>
  </div>
<% end %>

app/views/entries/index.html.erb
<div >
  <div>
    <div>
      <%= render @journal %>

      <%= link_to 'Back to journals', journals_path %>
    </div>
  </div>

  <% if notice.present? %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div>
    <h1>Entries</h1>
    <%= turbo_frame_tag Entry.new do %>
      <%= link_to 'New Entry', new_journal_entry_path(@journal) %>
    <% end %>
  </div>

  <div id="entries">
    <%= render @journal.entries %>
  </div>
</div>

app/views/entries/new.html.erb
<!-- app/views/journals/new.html.erb -->

<h4>New Entry</h4>

<%= turbo_frame_tag @entry do %>
  <div>
  <%= render "form", entry: @entry %>
  </div>
<% end %>

app/views/entries/update.turbo_stream.erb
<%= turbo_stream.update @entry do%>
  <%= render @entry %>
<% end %>

app/views/journals/_form.html.erb
<%= form_with(model: journal, class: "contents", id: "journal_form") do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, required: true, data: { "validation-message": "Please enter a name for the journal." } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/_journal.html.erb
<%= turbo_frame_tag journal do %>
  <p class="my-5">
    <%= journal.name %>
  </p>

  <% if action_name != "show" && controller_name!= 'entries'%>
    <%= button_to "Destroy",journal_path(journal), method: :delete %>
    <%= link_to "Show", journal_entries_path(journal), data: { turbo_frame: "_top" } %>
    <%= link_to 'Edit', edit_journal_path(journal) %>
    <hr class="mt-6">
  <% end %>
<% end %>

app/views/journals/create.turbo_stream.erb
<%= turbo_stream.prepend "journals" do %>
  <%= render @journal %>
<% end %>

<%= turbo_stream.replace "journal_form" do %>
  <%= render "form", journal: Journal.new %>
<% end %>

app/views/journals/edit.html.erb
<%= turbo_frame_tag @journal do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing journal</h1>

    <%= render "form", journal: @journal %>

    <%= link_to "Cancel", journals_path %>
  </div>
<% end %>

app/views/journals/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p id="notice"><%= notice %></p>
  <% end %>

  <div>
    <h1>Journals</h1>
    <%= turbo_frame_tag Journal.new do %>
      <%= link_to 'New Journal', new_journal_path %>
    <% end %>
  </div>

  <div id="journals" class="min-w-full">
    <%= render @journals %>
  </div>
</div>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= turbo_frame_tag @journal do %>
  <div>
  <h1>New journal</h1>

  <%= render "form", journal: @journal %>

  <%= link_to 'Cancel', journals_path %>
  </div>
<% end %>

app/views/journals/show.html.erb
<div>
  <div>
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <%= render @journal %>

    <%= link_to 'Back to journals', journals_path %>
  </div>
</div>

app/views/journals/update.turbo_stream.erb
<%= turbo_stream.update @journal do %>
  <%= render @journal %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalMicroservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>